/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  darkMode: ['class'],
  plugins: [],
  safelist: [
    '-mt-12',
    'absolute',
    'bg-green-500',
    'bg-red-500',
    'bg-white',
    'border-separate',
    'border-spacing-0',
    'duration-1000',
    'duration-200',
    'ease-out',
    'ease',
    'fa-circle-check',
    'fa-square-xmark',
    'group-hover:-translate-x-40',
    'h-32',
    'hover:bg-gradient-to-r',
    'hover:from-green-500',
    'hover:from-red-500',
    'hover:ring-2',
    'hover:ring-green-400',
    'hover:ring-offset-2',
    'hover:ring-red-400',
    'hover:to-green-400',
    'hover:to-red-400',
    'left-0',
    'ml-6',
    'opacity-10',
    'px-2',
    'right-0',
    'rotate-12',
    'shadow-2xl',
    'sticky',
    'transform',
    'transition-all',
    'translate-x-12',
    'w-8',
    'whitespace-nowrap',
    'z-50',
  ],
};
